<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateAnimaless extends Migration{
	public function up(){ 
 		Schema::create('animaless', function (Blueprint $table) { 
			$table->bigIncrements('id');
			$table->int('id');
			$table->string('nombre');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}